FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2

USER elasticsearch

COPY zip_files/readonlyrest-1.16.28_es6.4.2.zip /usr/share/elasticsearch/

# Search ReadonlyREST plugin
# https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#installing-the-plugin
RUN elasticsearch-plugin install --batch file:///usr/share/elasticsearch/readonlyrest-1.16.28_es6.4.2.zip

USER root
