apiVersion: v1
kind: Template
metadata:
  name: elasticsearch-search-guard-single-node
objects:
- kind: SecurityContextConstraints
  apiVersion: v1
  metadata:
    name: elasticsearch-scc
  allowPrivilegedContainer: true
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: RunAsAny
  fsGroup:
    type: RunAsAny
  supplementalGroups:
    type: RunAsAny
  allowedCapabilities:
    - IPC_LOCK
    - SYS_RESOURCE
  users:
  - system:serviceaccount:${NAMESPACE}:default

- kind: ConfigMap
  apiVersion: v1
  metadata:
    annotations:
      kompose.cmd: kompose --provider openshift convert -f docker-compose.yml --emptyvols
      kompose.version: 1.1.0 (36652f6)
    labels:
      io.kompose.service: elasticsearch
    name: elasticsearch-config
  data:
    elasticsearch.yml: |
      ---
      cluster.name: "${CLUSTER_NAME}"
      network.host: 0.0.0.0
      http.port: 9202
      transport.port: 9301
      discovery.type: single-node

- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      kompose.cmd: kompose --provider openshift convert -f docker-compose.yml --emptyvols
      kompose.version: 1.1.0 (36652f6)
    labels:
      io.kompose.service: kibana
    name: kibana-config
  data:
    kibana.yml: |
      ---
      server.name: kibana
      server.host: "0"
      server.port: 5602
      elasticsearch.hosts: ["http://elasticsearch:9202"]

- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      io.kompose.service: elasticsearch
    name: elasticsearch
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: elasticsearch
    serviceName: elasticsearch
    template:
      metadata:
        labels:
          io.kompose.service: elasticsearch
      spec:
        initContainers:
        - command:
          - sysctl
          - -w
          - vm.max_map_count=262144
          image: busybox:1.27.2
          imagePullPolicy: IfNotPresent
          name: init-sysctl
          resources: {}
          securityContext:
            privileged: true
        containers:
        - env:
          image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /_cluster/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: elasticsearch
          ports:
          - containerPort: 9202
            name: http
            protocol: TCP
          - containerPort: 9301
            name: transport
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: transport
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: storage
          - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            name: elasticsearch-config
            subPath: elasticsearch.yml
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
        restartPolicy: Always
        volumes:
        - configMap:
            defaultMode: 420
            name: elasticsearch-config
          name: elasticsearch-config
        - configMap:
            defaultMode: 384
            name: search-guard-configs
          name: search-guard-configs
    volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: ${ELASTICSEARCH_VOLUME_CAPACITY}
        storageClassName: ${STORAGECLASSNAME}
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kompose.cmd: kompose --provider openshift convert -f docker-compose.yml --emptyvols
      kompose.version: 1.1.0 (36652f6)
    labels:
      io.kompose.service: kibana
    name: kibana
  spec:
    replicas: 1
    selector:
      io.kompose.service: kibana
    strategy:
      resources: {}
      type: Rolling
    template:
      metadata:
        labels:
          io.kompose.service: kibana
      spec:
        containers:
        - image: docker.elastic.co/kibana/kibana-oss:7.10.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: kibana
          ports:
          - containerPort: 5602
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 7
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
          - mountPath: /usr/share/kibana/config/kibana.yml
            name: kibana-config
            subPath: kibana.yml
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
        restartPolicy: Always
        volumes:
        - configMap:
            defaultMode: 420
            name: kibana-config
          name: kibana-config
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
    labels:
      io.kompose.service: elasticsearch
    name: elasticsearch
  spec:
    host: ${ELASTICSEARCH_URL}
    port:
      targetPort: "9202"
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: elasticsearch
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      kompose.cmd: kompose --provider openshift convert -f docker-compose.yml --emptyvols
      kompose.version: 1.1.0 (36652f6)
    labels:
      io.kompose.service: kibana
    name: kibana
  spec:
    host: ${KIBANA_URL}
    port:
      targetPort: "5602"
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: kibana
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose --provider openshift convert -f docker-compose.yml --emptyvols
      kompose.version: 1.1.0 (36652f6)
    labels:
      io.kompose.service: elasticsearch
    name: elasticsearch
  spec:
    ports:
    - name: "9202"
      port: 9202
      protocol: TCP
      targetPort: 9202
    - name: "9301"
      port: 9301
      protocol: TCP
      targetPort: 9301
    selector:
      io.kompose.service: elasticsearch
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose --provider openshift convert -f docker-compose.yml --emptyvols
      kompose.version: 1.1.0 (36652f6)
    labels:
      io.kompose.service: kibana
    name: kibana
  spec:
    ports:
    - name: "5602"
      port: 5602
      protocol: TCP
      targetPort: 5602
    selector:
      io.kompose.service: kibana
    type: ClusterIP

parameters:
  - name: NAMESPACE
    displayName: Your project's namespace
    required: true 
  - name: CLUSTER_NAME
    displayName: Cluster name (cluster.name)
    value: docker-cluster
    required: true 
  - name: STORAGECLASSNAME
    displayName: Your storage class name (storageClassName) used in your cluster
    value: standard
    required: true
  - name: ELASTICSEARCH_VOLUME_CAPACITY
    displayName: Volume space available for data, e.g. 512Mi, 2Gi.
    value: 10Gi
    required: true
  - name: ELASTICSEARCH_URL
    displayName: ElasticSearch url
    required: true 
  - name: KIBANA_URL
    displayName: Kibana url
    required: true 
