apiVersion: v1
kind: Template
metadata:
  name: elasticsearch-search-guard-single-node
objects:
- kind: SecurityContextConstraints
  apiVersion: v1
  metadata:
    name: elasticsearch-scc
  allowPrivilegedContainer: true
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: RunAsAny
  fsGroup:
    type: RunAsAny
  supplementalGroups:
    type: RunAsAny
  allowedCapabilities:
    - IPC_LOCK
    - SYS_RESOURCE
  users:
  - system:serviceaccount:${NAMESPACE}:default

- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      io.kompose.service: elasticsearch
    name: elasticsearch
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: elasticsearch
    serviceName: elasticsearch
    template:
      metadata:
        labels:
          io.kompose.service: elasticsearch
      spec:
        initContainers:
        - command:
          - sysctl
          - -w
          - vm.max_map_count=262144
          image: busybox:1.27.2
          imagePullPolicy: IfNotPresent
          name: init-sysctl
          resources: {}
          securityContext:
            privileged: true
        containers:
        - env:
        - name: cluster.name
          value: opensearch-cluster
        - name: node.name
          value: opensearch-node1
        - name: bootstrap.memory_lock
          value: true
        - name: OPENSEARCH_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: DISABLE_INSTALL_DEMO_CONFIG
          value: true
        - name: DISABLE_SECURITY_PLUGIN
          value: true
        - name: discovery.type
          value: single-node
          #image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
          image: opensearchproject/opensearch:2.2.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: elasticsearch
          ports:
          - containerPort: ${{ES_HTTP_PORT}}
            name: http
            protocol: TCP
          - containerPort: ${{ES_TRANSPORT_PORT}}
            name: transport
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: transport
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
          - mountPath: /usr/share/opensearch/data
            name: storage
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
        restartPolicy: Always
    volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: ${ELASTICSEARCH_VOLUME_CAPACITY}
        storageClassName: ${STORAGECLASSNAME}
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: Route
  metadata:
    annotations:
    labels:
      io.kompose.service: elasticsearch
    name: elasticsearch
  spec:
    host: ${ELASTICSEARCH_URL}
    port:
      targetPort: "${ES_HTTP_PORT}"
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: elasticsearch
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose --provider openshift convert -f docker-compose.yml --emptyvols
      kompose.version: 1.1.0 (36652f6)
    labels:
      io.kompose.service: elasticsearch
    name: elasticsearch
  spec:
    ports:
    - name: "${ES_HTTP_PORT}"
      port: ${{ES_HTTP_PORT}}
      protocol: TCP
      targetPort: ${{ES_HTTP_PORT}}
    - name: "${ES_TRANSPORT_PORT}"
      port: ${{ES_TRANSPORT_PORT}}
      protocol: TCP
      targetPort: ${{ES_TRANSPORT_PORT}}
    selector:
      io.kompose.service: elasticsearch
    type: ClusterIP

parameters:
  - name: NAMESPACE
    displayName: Your project's namespace
    required: true 
  - name: CLUSTER_NAME
    displayName: Cluster name (cluster.name)
    value: docker-cluster
    required: true 
  - name: STORAGECLASSNAME
    displayName: Your storage class name (storageClassName) used in your cluster
    value: standard
    required: true
  - name: ELASTICSEARCH_VOLUME_CAPACITY
    displayName: Volume space available for data, e.g. 512Mi, 2Gi.
    value: 10Gi
    required: true
  - name: ELASTICSEARCH_URL
    displayName: ElasticSearch url
    required: true 
  - name: ES_HTTP_PORT
    displayName: Elasticsearch http port
    value: "9200"
    required: true
  - name: ES_TRANSPORT_PORT
    displayName: Elasticsearch transport port
    value: "9600"
    required: true