apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift convert -f docker-compose.yml --emptyvols
    kompose.version: 1.1.0 (36652f6)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    ---
    # https://github.com/deviantony/docker-elk/blob/searchguard/elasticsearch/config/elasticsearch.yml
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    discovery.zen.minimum_master_nodes: 1
    discovery.type: single-node
    ## Search Guard
    #
    searchguard.enterprise_modules_enabled: false

    searchguard.ssl.transport.pemcert_filepath: sgconfig/esnode.pem
    searchguard.ssl.transport.pemkey_filepath: sgconfig/esnode-key.pem
    searchguard.ssl.transport.pemtrustedcas_filepath: sgconfig/root-ca.pem
    searchguard.ssl.transport.enforce_hostname_verification: false

    searchguard.authcz.admin_dn:
      - CN=kirk,OU=client,O=client,l=test,C=de

    # disable Search Guard without removing it (Please use this feature carefully.)
    # ref: https://docs.search-guard.com/latest/disabling-removing-search-guard
    # searchguard.disabled: true
